### PR TITLE
feat: adds support for a custom diff message

### LINKED ISSUE #425: pass custom fail message
Currently when tests are failing for any reason we get this message in terminal:

> Inspect your code changes, re-run with `-U` to update them

The issue with this message is that in some cases running the reg-cli command is used with an npm/yarn script.  
For example - `yarn test:visual`.

So developers that are using the repo think they need to run `yarn test:visual -U` but this will just run the test again, what they really need to run is another dedicated script for updating e.g: `yarn test:visual:update`.

It would be great to pass reg-cli a fail message (we can also pass success message if you think its needed) that will be used in case of a fail. The default message can be the message we have today.

### PR DESCRIPTION
**Pull request by sag1v**
## What does this change?

resolve #425 

adds support for a custom diff message

## References

#425

### CODE REVIEW

**Comment by sag1v** [comment]
@bokuweb can we move forward with this? :)

**Comment by bokuweb** [comment]
sorry for late. i'll review it.

**Review by bokuweb — APPROVED** [review]
LGTM 👍

**Comment by sag1v** [comment]
@bokuweb Thanks! I'm sorry but i just realized that i forgot to add it to the README docs. 🤦‍♂️

**Pull request merged**
