### PR TITLE
(fix) Enable reg-cli to delete images whose name contain glob characters

### PR DESCRIPTION
**Pull request by nagashimam**
# What does this change?

This change enables reg-cli to delete image whose name contains glob character. 

# Why do I need this change?

I take screenshots of my Storybook  with storycap. I have stories whose names are like "Login(LGN001)" where "LGN001" is the ID of the screen in specification.  Then I run reg-cli to those screenshots. 

The problem is their screenshots are not deleted even after those screens are removed from requirements and my Storybook or their story names are changed. They keep showing up in 「deleted items」 section in ​report.html  

# What can I check for bug fixes?

I changed the name of sample image in resource directory. You can see test fails in [this commit](https://github.com/reg-viz/reg-cli/commit/dd5e3e678c2ac2a0c4d6676682247431b2a44753), but passes in [this commit](https://github.com/reg-viz/reg-cli/commit/b716ab38ff12d80708b10072fbfc4507545612b0)

### CODE REVIEW

**Comment by bokuweb** [comment]
@nagashimam Sorry for late.
Thanks for your PR. Looks good.
However `should delete from /expected when they are missing from /actual with `-U` option File sample(cal).png was not deleted from /expected` test is failed on windows. (https://ci.appveyor.com/project/bokuweb/reg-cli/builds/40563853)

Could you please check this error?

**Comment by nagashimam** [comment]
Ah, I only tested on my Mac. I'll fix the error and make sure this works both on Mac and Windows.

**Comment by nagashimam** [comment]
Just so you know, my mac got broken and I haven't figured out why my branch doesn't work with Windows. It'll take some more time but I'll let you know when I'm done

**Comment by nagashimam** [comment]
@bokuweb 
There was mistake in how to escape glob. I fixed it and now it seems working as far as I test with my mac(real device) and windows server(google compute engine)

Could you take a look at it?

**Review by bokuweb — APPROVED** [review]
@nagashimam Thanks :)

**Pull request merged**
